language: python
python:
  - '2.7'
install:
  - python setup.py sdist --formats=zip
  - find ./dist -iname "*.zip" -print0 | xargs -0 pip install
notifications:
  email:
    recipients:
      - matti@ccpgames.com
    on_success: change
    on_failure: always

addons:
  artifacts:
    key: "AKIAIUW36UNJJPK5C6MA"
    secret: "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"
    bucket: "vkb-builds"

